Binding
weweb-assets/ww-form-dropdown pull request #10
Opened 2021-12-08 23:40 UTC by kevinbarfleur

2021-12-09 15:50 UTC, Dams-d approved these changes

2021-12-09 16:00 UTC, AurelieV requested changes

2021-12-10 17:53 UTC, AurelieV requested changes

2021-12-10 17:53 UTC, AurelieV commented on src/wwElement.vue
> +        v-model="internalValue"
value non?

2021-12-10 18:04 UTC, kevinbarfleur commented on src/wwElement.vue
> +        v-model="internalValue"
fixed

2021-12-16 18:11 UTC, merged