Normalize input
weweb-assets/ww-form-dropdown pull request #13
Opened 2022-01-07 10:52 UTC by kevinbarfleur

2022-01-07 11:17 UTC, AurelieV approved these changes

2022-01-07 11:17 UTC, AurelieV commented on src/wwElement.vue
> +                return this.variableValue;
maybe cast this to a string?

2022-01-07 11:17 UTC, AurelieV commented on src/wwElement.vue
> +            if (value !== undefined) this.value = value;
pourquoi le cas undefined?

2022-01-07 11:17 UTC, AurelieV commented on ww-config.js
>                  en: 'Initial value',
label à changer

2022-01-07 11:33 UTC, AurelieV commented
@kevinbarfleur il manque aussi le changement de version

2022-01-07 13:18 UTC, kevinbarfleur commented on src/wwElement.vue
> +            if (value !== undefined) this.value = value;
Je me suis dit que c'était plus safe, ça sert à rien ?

2022-01-07 13:51 UTC, Dams-d approved these changes

2022-01-07 15:47 UTC, Kramerbaf requested changes

2022-01-07 15:47 UTC, Kramerbaf commented on ww-config.js
>                  en: 'Initial value',
@kevinbarfleur

2022-01-09 14:13 UTC, AurelieV requested changes

2022-01-09 14:13 UTC, AurelieV commented on src/wwElement.vue
> +            this.$refs.input.value = this.options.find(
pourquoi cette ligne?

2022-01-09 14:37 UTC, kevinbarfleur commented on src/wwElement.vue
> +            this.$refs.input.value = this.options.find(
Effectivement, c'est géré par le v-model, je note !

2022-01-10 09:54 UTC, AurelieV approved these changes

2022-01-10 10:00 UTC, merged